import localfont from "next/font/local"
import "../globals.css";
import Navbar from "@/Shared/Navbar";
import Footer from "@/Shared/Footer";
import AuthProvider from "@/Provider/AuthProvider";

const allianceNo2 = localfont(
  {
    src: [
      {
        path: '../../../public/fonts/AllianceNo2-Regular.ttf',
        weight: '400',
        style: 'normal',
      },
    ]
  }
);

export const metadata = {
  title: "Afs Games",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={allianceNo2.className}>
        <main className="pt-[10px] bg-[#FFFFF8]">
          <AuthProvider>
            <Navbar />
            {children}
            <Footer />
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
